# Git Aliases
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gds='git diff --staged'
alias gp='git pull'
alias gs='git status'
alias gst='git stash'

# Shell Aliases
alias cat='bat'
alias cp='cp -i'
alias jobs='jobs -l'
alias la='ls -A'
alias ll='ls -AlF'
alias ls='ls -F'
alias mrc='mise run checkout'
alias mrcq='mrc > /dev/null 2>&1 &'
alias mv='mv -i'
alias rm='rm -i'
